### ISSUE TITLE
怎么给Fongmi 的tvbox使用呢？

### ISSUE THREAD

**Issue by OopsAngela** [stanlyshi/tvbox-cfg#1]
怎么给Fongmi 的tvbox使用呢？

**Comment by stanlyshi** [comment]
点击json文件，点击raw，打开文件的原始路径，把网址添加到tvbox源就好了。
例如：https://raw.githubusercontent.com/stanlyshi/tvbox-cfg/master/js.json
如果需要代理，在网址前面加上代理。
例如：https://mirror.ghproxy.com/https://raw.githubusercontent.com/stanlyshi/tvbox-cfg/master/js.json
